version: '3'

services:
  db:
    image: postgres
    volumes:
      - data-volume:/var/lib/postgresql/data
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: hugoblog
      POSTGRES_DB: blog_db
  web-init:
    build: .
    command: /code/initserver.sh
    volumes:
      - .:/code
    depends_on:
      - db
  web:
    build: .
    user: nobody
    command: /code/runserver.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - web-init
volumes:
  data-volume:
