# Generated by Django 2.1.5 on 2019-01-13 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20190111_1907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('can_create', 'Create Posts'), ('can_edit', 'Edit Posts'))},
        ),
    ]
