# Generated by Django 2.1.5 on 2019-01-19 02:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 19, 2, 37, 41, 375291, tzinfo=utc), verbose_name='date published'),
        ),
    ]
