# Generated by Django 2.1.5 on 2019-01-28 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20190119_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_text',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
